sudo: false
language: rust
cache: cargo
rust:
- nightly
- beta
- stable
env:
  flags=--all-features
matrix:
  allow_failures:
  - rust: nightly
  include:
    # should also build with no features, as well as individual features selected
    - rust: stable
      env: flags=
    - rust: stable
      env: flags=--features=google
    - rust: stable
      env: flags=--features=mock
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build $flags &&
  travis-cargo test $flags &&
  travis-cargo doc $flags
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
notifications:
  slack:
    secure: glnUSyijPfYikgMqafee8Bs1ecAB0eNu6YXue5tNivQF10/++gDebUZflXbYb9C8661qQLUWTDssdK4gPpNZpvVvkIvxWfWiFgM+CLJVGCZhEz7aYf/DEYGldq94UHAimTKqzQ64WwlIHn5IakxQUZBRa6/N+t+YHmIXVLGSC+8VFgHBs9lg2NvZ2MQ+iaJiiBzE9+xFD5jkKr1IRVVgfiJ/H82HhF5dGh8/l2k4NQ6x2srIb1OhaKNO+ZnCZMvGKc2ryNTTucEQHlxFCAZNnkNTgxU5fKMsM9Sg5+M3g8GA3tS4e/X8cB3hvqD86/NMrbpk4+pFQ1yTPeY1UPDadwkPrZYOwwnlJNUWAbwzz9zcFUkIzoI7xJpVoZnlVxMvko1VT62EzTdTbUZDJCkDsyy4DkNx5Nhs5F1ZFg4LfCZgvH3+7FNsZN2M5fTTcOF7BIUFjQT5pO9vjoY480UPOwEA64v3g2l8tGM2zXKKsTgsCtiCMRO8J0RCcBhM3pZ9q8O7YY7M9epS8Frp8PCYZaO7k0dedAAXXLUtGw+wJJeHyLtA9vzzZy3P7lGsRmz6PH6BF7MreyToYStNHndgfewKxXjXBE5i/US5zFrmk9Bquf7v8s7UAcM6VsOpBEsbKbTvl2Ym4+T8LpaFtOJ1lq/pP13aIQj9gRa01Mi22rI=
